name: flow
description: A personal finance tracking app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  csv: ^5.1.1
  file_picker: ^6.1.1
  file_saver: 0.2.8
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  fuzzy: ^0.5.1
  go_router: ^13.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  local_settings: ^0.3.1
  mask_text_input_formatter: ^2.7.0
  material_symbols_icons: ^4.2671.0
  moment_dart: ^1.1.0
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.3.1
  oktoast: ^3.4.0
  path: ^1.8.3
  path_provider: ^2.1.1
  salomon_bottom_bar: ^3.3.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  simple_icons: ^10.1.3
  url_launcher: ^6.2.1
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.7

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  objectbox_generator: ^2.3.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/l10n/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

objectbox:
  output_dir: objectbox
